# Generated by Django 4.1.4 on 2023-08-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
